// <auto-generated />
using InfluencePWA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfluencePWA.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("InfluencePWA.Data.Models.Principle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Law")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrincipleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrincipleTypeId");

                    b.ToTable("Principles");
                });

            modelBuilder.Entity("InfluencePWA.Data.Models.PrincipleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrincipleTypes");
                });

            modelBuilder.Entity("InfluencePWA.Data.Models.Principle", b =>
                {
                    b.HasOne("InfluencePWA.Data.Models.PrincipleType", "PrincipleType")
                        .WithMany("Principles")
                        .HasForeignKey("PrincipleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrincipleType");
                });

            modelBuilder.Entity("InfluencePWA.Data.Models.PrincipleType", b =>
                {
                    b.Navigation("Principles");
                });
#pragma warning restore 612, 618
        }
    }
}
